name: Build and Deploy Jupyter Book

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter-book

      - name: Build Jupyter Book
        run: |
          jupyter-book build docs/libro

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/libro/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v4
